# Generated by Django 4.1.2 on 2022-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='venue',
            field=models.CharField(choices=[(1, 'The Manor, Mumbai'), (2, 'Panchavatti, Goa'), (3, 'Chapslee, Himachal Pradesh'), (4, 'Casa Susegad, Goa'), (5, 'Centaur Hotel, New Delhi'), (6, 'Hotel Airport International, Mumbai'), (7, 'Hotel Airport Ashok, Kolkata'), (8, 'Leela Palace Hotel, Bangalore'), (9, 'Le Royal Meridien Hotel, Chennai'), (10, 'The Residence Apartment, Mumbai')], default=1, max_length=100),
        ),
    ]
