# Generated by Django 4.1.2 on 2022-11-21 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='venue',
            field=models.CharField(choices=[('The Manor, Mumbai', 'The Manor, Mumbai'), ('Panchavatti, Goa', 'Panchavatti, Goa'), ('Chapslee, Himachal Pradesh', 'Chapslee, Himachal Pradesh'), ('Casa Susegad, Goa', 'Casa Susegad, Goa'), ('Centaur Hotel, New Delhi', 'Centaur Hotel, New Delhi'), ('Hotel Airport International, Mumbai', 'Hotel Airport International, Mumbai'), ('Hotel Airport Ashok, Kolkata', 'Hotel Airport Ashok, Kolkata'), ('Leela Palace Hotel, Bangalore', 'Leela Palace Hotel, Bangalore'), ('Le Royal Meridien Hotel, Chennai', 'Le Royal Meridien Hotel, Chennai'), ('The Residence Apartment, Mumbai', 'The Residence Apartment, Mumbai')], max_length=100),
        ),
    ]
