# Generated by Django 4.1.2 on 2022-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hangout',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
