# Generated by Django 4.1.2 on 2022-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_hangout_rate_hangout_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
