# Generated by Django 4.1.2 on 2022-11-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_hangout_rate_alter_hangout_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
