# Generated by Django 4.1.2 on 2022-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_hangout_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='type',
            field=models.CharField(default='hotel', max_length=10),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
